### PR TITLE
feat: status codes and errors

### PR DESCRIPTION
**Pull request by gjj**
In this MR, added the descriptions of status codes and errors for:

- DOCUMENT_STATUS Fragment
  - UNEXPECTED_ERROR
  - DOCUMENT_NOT_ISSUED
  - DOCUMENT_NOT_MINTED
  - CONTRACT_ADDRESS_INVALID
  - ETHERS_UNHANDLED_ERROR
  - SKIPPED
  - DOCUMENT_REVOKED
  - INVALID_ARGUMENT
  - CONTRACT_NOT_FOUND
  - SERVER_ERROR

### CODE REVIEW

**Comment by gjj** [comment]
image

However it looks a bit too colourful... don't you think?

**Comment by Nebulis** [comment]
Good initiative.

I'm good with the content and we can discuss on the color issue however I wonder if we should really add this into **this** documentation:
- the title is very generic (could be applied to any lib) but in the end it targets a specific lib
- there is already something about is verify in the advanced part (should we merge)
- this will be broken everytime because we will forget to update the doc -> should we keep it in oa verify documentation?

**Comment by gjj** [comment]
@Nebulis I think you're right, that we should keep it in `oa-verify`. So that I can write a blogpost in OpenCerts blog that references our updates in `oa-verify`.

**Comment by Nebulis** [comment]
Sounds like a good idea

**Comment by gjj** [comment]
I've since published the new errors in https://github.com/OpenCerts/opencerts-documentation/pull/122/files

See https://docs.opencerts.io/blog/2020/10/08/new-error-types

**Pull request closed without merging**
