### PR TITLE
fix: update docusaurus search with algolia credentials

### PR DESCRIPTION
**Pull request by isaackps**
## In this PR:
- update docusaurus to latest beta version
- update algolia search with required appId and API key

### CODE REVIEW

**Comment by simboonlong** [comment]
able to request app transfer to `dltgovtech@gmail.com` too?

looks like some esm problem interfering with build, might need to narrow down which dep is causing that

**Comment by isaackps** [comment]
> able to request app transfer to `dltgovtech@gmail.com` too? [guide](https://support.algolia.com/hc/en-us/articles/4406981844113-How-do-I-transfer-ownership-of-my-account-to-someone-else-) <- i went through this process once. from exp it might take awhile again
> 
> meanwhile, looks like some esm problem interfering with build, might need to narrow down which dep is causing that

ok sure! will do the request, and will find the issue.

**Comment by simboonlong** [comment]
can split this pr? remote plugin, algolia cred

**Comment by isaackps** [comment]
> can split this pr? remote plugin, algolia cred

cant leh, somehow the old remote plugin is interfering with the new algolia version, where it will have build error.

**Comment by simboonlong** [comment]
can u do that? this pr is hard to understand what's intentional changes VS what's not

**Comment by isaackps** [comment]
> can u do that? this pr is hard to understand what's intentional changes VS what's not

but if i do that, the build will not pass leh. netlify will throw an error.

**Comment by cavacado** [comment]
hmm @isaackps whats stopping you from doing the algo cred pr first, getting it merged, then after that opening another pr with the new remote plugin changes?

**Comment by isaackps** [comment]
> hmm @isaackps whats stopping you from doing the algo cred pr first, getting it merged, then after that opening another pr with the new remote plugin changes?

sorry i misread, ok can i'll do the algo cred pr 1st then do the remote plugin changes. cos i was thinking that when i do the algo cred i will be updating the algo library which will break the build. 

ok so ill update with just the new algo cred 1st then do the rest in another pr.

**Review by simboonlong — APPROVED** [review]
let's get this in first, may need to revisit on other solutions in handling remote md in future

**Pull request merged**
